### ISSUE TITLE
La tarea 2

### ISSUE THREAD

**Issue by Makova** [oslugr/0agit#2]
Conceptos básicos y unos pocos comandos. Si puede ser.

**Comment by JJ** [comment]
Bueno, pero "sin meterse en comandos". Es decir, todos los comandos son git esto git lo otro, tienen tales opciones, qué significa hacer push, qué commit... pero sin deci r"esto se hace git commit" ni nada

**Comment by Makova** [comment]
Pues no se si es que estoy demasiado espeso pero no me entero de lo que me has explicado.

**Comment by JJ** [comment]
Que expliques los conceptos: qué se puede hacer, más que como hacerlo.

2014-05-21 20:05 GMT+02:00 Manu notifications@github.com:

> Pues no se si es que estoy demasiado espeso pero no me entero de lo que me
> has explicado.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/oslugr/0agit/issues/2#issuecomment-43793133
> .

## 

JJ

**Comment by Makova** [comment]
Si, lo más importante es el concepto. Siempre que nombro el _concepto_ me
acuerdo de la película "Airbag".
Esto lo hago en local y lo voy subiendo a ese repositorio ¿No?. Creo una
carpeta _Conceptos básicos de git_ y dentro archivo _loquesea.md
http://loquesea.md_ con el concepto.

El 21 de mayo de 2014, 20:13, Juan Julián Merelo Guervós <
notifications@github.com> escribió:

> Que expliques los conceptos: qué se puede hacer, más que como hacerlo.
> 
> 2014-05-21 20:05 GMT+02:00 Manu notifications@github.com:
> 
> > Pues no se si es que estoy demasiado espeso pero no me entero de lo que
> > me
> > has explicado.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/oslugr/0agit/issues/2#issuecomment-43793133>
> > .
> 
> ## 
> 
> JJ
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/oslugr/0agit/issues/2#issuecomment-43794018
> .

## 

## Manu

**Comment by JJ** [comment]
cafe2.md, por ejemplo, para que tengan todos el mismo nombre.

El 21 de mayo de 2014, 20:23, Manu notifications@github.com escribió:

> Si, lo más importante es el concepto. Siempre que nombro el _concepto_ me
> acuerdo de la película "Airbag".
> Esto lo hago en local y lo voy subiendo a ese repositorio ¿No?. Creo una
> carpeta _Conceptos básicos de git_ y dentro archivo _loquesea.md
> http://loquesea.md_ con el concepto.
> 
> El 21 de mayo de 2014, 20:13, Juan Julián Merelo Guervós <
> notifications@github.com> escribió:
> 
> > Que expliques los conceptos: qué se puede hacer, más que como hacerlo.
> > 
> > 2014-05-21 20:05 GMT+02:00 Manu notifications@github.com:
> > 
> > > Pues no se si es que estoy demasiado espeso pero no me entero de lo
> > > que
> > > me
> > > has explicado.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/oslugr/0agit/issues/2#issuecomment-43793133>
> > > .
> > 
> > ## 
> > 
> > JJ
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/oslugr/0agit/issues/2#issuecomment-43794018>
> > .
> 
> ## 
> 
> ## Manu
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/oslugr/0agit/issues/2#issuecomment-43795363
> .

## 

JJ
