### ISSUE TITLE
¿4 y 5 no deberían estar invertidos?

### ISSUE THREAD

**Issue by psicobyte** [oslugr/0agit#3]
Uso de clientes. Trabajo en local. Sincronizar cambios.
Añadir ficheros. Quitar ficheros. Qué significa todo ello.

¿Qué cambios vas a sincronizar si aún no sabes agregar archivos?

**Comment by JJ** [comment]
No necesariamente. Los cambios sólo sobre los ficheros existentes.

El 21 de mayo de 2014, 20:16, Psicobyte notifications@github.com escribió:

> Uso de clientes. Trabajo en local. Sincronizar cambios.
> Añadir ficheros. Quitar ficheros. Qué significa todo ello.
> 
> ¿Qué cambios vas a sincronizar si aún no sabes agregar archivos?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/oslugr/0agit/issues/3
> .

## 

JJ
